language: objective-c
osx_image: xcode8.3
sudo: false

install:
  - wget https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-osx-gs-x64.pkg -O ~/dotnet-sdk-2.0.0-osx-gs-x64.pkg
  - sudo installer -pkg ~/dotnet-sdk-2.0.0-osx-gs-x64.pkg -target /
  - PATH="/usr/local/share/dotnet/:$PATH"
  - dotnet --version

script:
  - dotnet restore src\Portable.Licensing\Portable.Licensing.csproj
  - dotnet build src\Portable.Licensing\Portable.Licensing.csproj -c Release
  - dotnet pack src\Portable.Licensing\Portable.Licensing.csproj -c Release --version-suffix r$TRAVIS_BUILD_NUMBER
  - dotnet test src\Portable.Licensing.Tests\Portable.Licensing.Tests.csproj
