image: Visual Studio 2017

before_build:
  - dotnet restore src\Portable.Licensing\Portable.Licensing.csproj

build_script:
  - dotnet build src\Portable.Licensing\Portable.Licensing.csproj -c Release
  - dotnet pack src\Portable.Licensing\Portable.Licensing.csproj -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%

on_success:
  - ps: Push-AppVeyorArtifact imobiledevice-net\bin\Debug\imobiledevice-net.1.2.1-r$($env:APPVEYOR_BUILD_NUMBER).nupkg
