image: Visual Studio 2017

before_build:
  - dotnet restore src\Portable.Licensing\Portable.Licensing.csproj

build_script:
  - dotnet build src\Portable.Licensing\Portable.Licensing.csproj -c Release
  - dotnet pack src\Portable.Licensing\Portable.Licensing.csproj -c Release

test_script:
  - dotnet test src\Portable.Licensing.Tests\Portable.Licensing.Tests.csproj

on_success:
  - ps: Push-AppVeyorArtifact src\Portable.Licensing\bin\Release\CoreCompat.Portable.Licensing.*.nupkg
